---
- include: add_user.yml
- include: lua.yml

- name: install pkg
  yum: pkg={{ item }} state=latest
  with_items:
    - gcc
    - gcc-c++
    - openssl-devel
    - pcre-devel
    - zlib-devel

- name: copy tengine
  unarchive: src=tengine-2.2.0.tar.gz dest=/data creates=tengine-2.2.0
  register: tengine_status


- name: install tengine
  shell: cd /data/tengine-2.2.0 && ./configure --prefix=/data/nginx --user={{nginx_user}} --group={{nginx_group}} --with-http_lua_module --with-jemalloc --with-http_gzip_static_module --with-http_realip_module --with-http_stub_status_module --with-http_concat_module --with-ld-opt="-Wl,-rpath,$LUAJIT_LIB" && make && make install

- name: copy nginx start file
  copy: src=nginx dest=/etc/init.d/nginx owner={{nginx_user}} group={{nginx_group}} mode=700

- name: conf nginx config file
  template: src=nginx.conf.j2 dest=/data/nginx/conf/nginx.conf owner={{nginx_user}} group={{nginx_group}} mode=700
  notify: restart nginx
