---
#zookeeper
zookeeper_client_port: "2181"
zookeeper_peers_nodes: "
        {%- if zookeeper_peers is defined -%}
            {% for host in zookeeper_peers %}{{host}}:{{zookeeper_client_port}}{% if not loop.last %},{% endif %}{% endfor %}
        {%- else -%}
            {%- for host in groups['zookeeper'] -%}{{ host }}:{{zookeeper_client_port}}{% if not loop.last %},{% endif %}{% endfor %}             
        {%- endif -%}"
#common
mesosphere_rpm_url: http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm
mesos_cluster_name: "zgcluster"
mesos_ip: "{{ ansible_default_ipv4.address }}"
mesos_hostname: "{{ ansible_default_ipv4.address }}"
mesos_log_location: "/var/log/mesos"
mesos_ulimit: "-n 8192"
mesos_zookeeper_masters: "zk://{{ zookeeper_peers_nodes }}/mesos"
mesos_option_prefix: "MESOS_"
# Defaults file for mesos-salve
mesos_executor_registration_timeout: "5mins"
mesos_containerizers: "docker,mesos"
mesos_docker_remove_delay: "1mins"
mesos_slave_port: "5051"
mesos_work_dir: "/var/lib/mesos"
mesos_log_dir: "/var/log/mesos"

# Defaults file for mesos-master
mesos_master_port: 5050
mesos_master_work_dir: "/var/lib/mesos"
mesos_master_offer_timeout: 30secs

mesos_master_nodes: "
{%- if mesos_masters_list is defined -%}
    {{mesos_masters_list}}
{%- else -%}
    {{groups['mesos_masters']}}
{%- endif -%}"

# The Mesos quorum value is based on the number of Mesos Masters. Take the
# number of masters, divide by 2, and round-up to nearest integer. For example,
# if there are 1 or 2 masters the quorum count is 1. If there are 3 or 4
# masters then the quorum count is 2. For 5 or 6 masters it's 3 and so on.

mesos_quorum: "
{% if mesos_master_quorum is defined %}
{{ mesos_master_quorum }}
{% else %}
{{ (mesos_master_nodes|count / 2)| round(0, 'ceil') | int }}
{%- endif -%}"
