---
  - name: copy gateway-web
    copy: src=gateway-web.war dest=/data/tomcat1/webapps/gateway-web.war owner=app group=app
    register: file_status

  - name: stop and rm  gateway-web 
    shell: /usr/local/bin/tomde 1 rm gateway-web && mkdir -p /data/rollback/`date "+%Y%m%d"`
    when: file_status.changed == true

  - name: start gateway-web
    shell: nohup /usr/local/bin/tomde 1 restart &
    tags: restart
  - action: uri url=http://127.0.0.1:8081/gateway-web/healthCheck return_content=yes
    register: httpcode
    until: httpcode.status == 200
    retries: 3
    delay: 15
    ignore_errors: yes
    tags: restart
  - name: rollback
    shell: /usr/local/bin/tomde 1 rm && mv {{ file_status['backup_file'] }} gateway-web.war
    notify: restart tomcat
    when: httpcode.status != 200
    register: rollback_status

  - name: backup gateway-web
    shell: cd /data/tomcat1/webapps && mv {{ file_status['backup_file'] }} /data/rollback/`date "+%Y%m%d"`/gateway-web_`date "+%H%M%S"`.war && echo /data/rollback/`date "+%Y%m%d"`/gateway-web_`date "+%H%M%S"`.war > /data/rollback/gateway.txt
    when: rollback_status.changed == false and file_status.changed == true
