---
- name: restart flannel
  service: name=flanneld state=restarted
  notify:
    - delete docker0
    - restart docker

- name: delete docker0
  command: ip link delete docker0
  ignore_errors: yes

- name: restart docker
  service: name=docker state=restarted

