---
- hosts: {{project}}
  gather_facts: False
  become: yes
  become_user: app
  tasks:
    - name: stop {{project}}
      shell: /usr/local/bin/tomde 1 rm

    - name: copy {{project}}
      shell: cp `cat /data/rollback/gateway.txt` {{ project_dir }}/gateway-web.war 
      register: status

    - name: start
      shell: nohup /usr/local/bin/tomde 1 restart &
      when: status.changed == true 

    - action: uri url=http://127.0.0.1:8081/gateway-web/healthCheck return_content=yes
      register: httpcode
      until: httpcode.status == 200
      retries: 3
      delay: 15
      ignore_errors: yes