---
- name: config tomcat1 server.xml
  copy: src=server1.xml dest=/data/tomcat1/conf/server.xml
  notify: restart tomcat1
  tags: tomcat_conf

- name: config tomcat1 catalina
  copy: src=catalina.sh dest=/data/tomcat1/bin/catalina.sh
  notify: restart tomcat1
  tags: tomcat_conf
