---
  - name: copy job-web
    copy: src=job-web.war dest=/data/tomcat1/webapps/job-web.war owner=app group=app
    register: file_status

  - name: stop and rm  job-web 
    shell: /usr/local/bin/tomde 1 rm job-web && mkdir -p /data/rollback/`date "+%Y%m%d"`
    when: file_status.changed == true

  - name: start job-web
    shell: nohup /usr/local/bin/tomde 1 restart &
    tags: restart
  - action: uri url=http://127.0.0.1:8081/job-web/healthCheck return_content=yes
    register: httpcode
    until: httpcode.status == 200
    retries: 3
    delay: 15
    ignore_errors: yes
    tags: restart
  - name: rollback
    shell: /usr/local/bin/tomde 1 rm && mv {{ file_status['backup_file'] }} job-web.war
    notify: restart tomcat
    when: httpcode.status != 200
    register: rollback_status

  - name: backup job-web and version
    shell: cd /data/tomcat1/webapps && mv {{ file_status['backup_file'] }} /data/rollback/`date "+%Y%m%d"`/job-web_`date "+%H%M%S"`.war && echo /data/rollback/`date "+%Y%m%d"`/job-web_`date "+%H%M%S"`.war > /data/rollback/job.txt
    when: rollback_status.changed == false and file_status.changed == true
